"""Unit tests for the fingerprint-matcher module.

Covers:
    1. Fingerprint matching (same image → match, different images → lower score)
    2. Spoof detection (real-ish image → not spoof, blank image → spoof)
    3. Impossible-travel anomaly detection
"""
import os
import sys
import unittest
from datetime import datetime, timedelta

# ---------------------------------------------------------------------------
# Make sure we can import sibling modules when running from the
# fingerprint-matcher directory.
# ---------------------------------------------------------------------------
THIS_DIR = os.path.dirname(os.path.abspath(__file__))
if THIS_DIR not in sys.path:
    sys.path.insert(0, THIS_DIR)

from dataset_loader import load_image
from matcher import compare_fingerprints
from spoof_check import check_for_spoof
from anomaly_check import check_impossible_travel

# ---------------------------------------------------------------------------
# Paths to sample images (generated by ``generate_samples.py``)
# ---------------------------------------------------------------------------
SAMPLE_DIR = os.path.join(THIS_DIR, "sample_images")
FINGER1 = os.path.join(SAMPLE_DIR, "finger1.png")
FINGER1_COPY = os.path.join(SAMPLE_DIR, "finger1_copy.png")
FINGER2 = os.path.join(SAMPLE_DIR, "finger2.png")
BLANK = os.path.join(SAMPLE_DIR, "blank.png")


class TestDatasetLoader(unittest.TestCase):
    """Tests for ``dataset_loader.load_image``."""

    def test_load_valid_image(self):
        img = load_image(FINGER1)
        self.assertIsNotNone(img)
        self.assertEqual(len(img.shape), 2, "Image should be 2-D (grayscale)")

    def test_load_missing_image_raises(self):
        with self.assertRaises(FileNotFoundError):
            load_image("does_not_exist.png")


class TestMatcher(unittest.TestCase):
    """Tests for ``matcher.compare_fingerprints``."""

    def test_same_image_matches(self):
        """Comparing an image with its exact copy should produce a high
        score and ``is_match=True``."""
        score, is_match = compare_fingerprints(FINGER1, FINGER1_COPY)
        self.assertTrue(is_match, f"Expected match, got score={score:.3f}")
        self.assertGreater(score, 0.4)

    def test_different_images_lower_score(self):
        """Two different fingerprint images should produce a lower match
        score than two identical ones."""
        score_same, _ = compare_fingerprints(FINGER1, FINGER1_COPY)
        score_diff, _ = compare_fingerprints(FINGER1, FINGER2)
        self.assertLess(
            score_diff, score_same,
            "Different prints should score lower than identical ones",
        )


class TestSpoofCheck(unittest.TestCase):
    """Tests for ``spoof_check.check_for_spoof``."""

    def test_real_image_not_spoof(self):
        """A synthetic ridge image should NOT be flagged as a spoof."""
        is_spoof, reason = check_for_spoof(FINGER1)
        self.assertFalse(is_spoof, f"Should not be spoof: {reason}")

    def test_blank_image_is_spoof(self):
        """A blank white image should be flagged as a spoof."""
        is_spoof, reason = check_for_spoof(BLANK)
        self.assertTrue(is_spoof, f"Blank image should be spoof: {reason}")


class TestAnomalyCheck(unittest.TestCase):
    """Tests for ``anomaly_check.check_impossible_travel``."""

    def test_no_previous_trip(self):
        """With no previous trip, there is nothing anomalous."""
        is_anomaly, reason = check_impossible_travel(
            user_id="U001",
            new_station_id="S1",
            new_timestamp=datetime.now(),
            last_trip=None,
        )
        self.assertFalse(is_anomaly)

    def test_plausible_travel(self):
        """Travel with enough elapsed time should be plausible."""
        now = datetime.now()
        last_trip = {"station_id": "S1", "timestamp": now - timedelta(minutes=30)}
        is_anomaly, reason = check_impossible_travel(
            user_id="U001",
            new_station_id="S2",
            new_timestamp=now,
            last_trip=last_trip,
        )
        self.assertFalse(is_anomaly, f"Should be plausible: {reason}")

    def test_impossible_travel(self):
        """Arriving at a distant station just 1 minute later should be
        flagged as impossible."""
        now = datetime.now()
        last_trip = {"station_id": "S1", "timestamp": now - timedelta(minutes=1)}
        is_anomaly, reason = check_impossible_travel(
            user_id="U001",
            new_station_id="S4",  # min 20 min away from S1
            new_timestamp=now,
            last_trip=last_trip,
        )
        self.assertTrue(is_anomaly, f"Should be impossible: {reason}")

    def test_timestamp_in_past(self):
        """A new timestamp earlier than the last trip should be flagged."""
        now = datetime.now()
        last_trip = {"station_id": "S1", "timestamp": now}
        is_anomaly, reason = check_impossible_travel(
            user_id="U001",
            new_station_id="S2",
            new_timestamp=now - timedelta(minutes=10),
            last_trip=last_trip,
        )
        self.assertTrue(is_anomaly, f"Past timestamp should be anomaly: {reason}")


if __name__ == "__main__":
    unittest.main()
